### ISSUE TITLE
ERROR: Failed parsing Certificate

### ISSUE THREAD

**Issue by shavster** [jr-b/amazon-reviews-scraper#1]
This was working, but i now get this error:

[0108/123241.680:ERROR:cert_issuer_source_aia.cc(34)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

**Comment by jr-b** [comment]
Hey @shavster,

I'm not having this issue on my side. From a quick Google search, that seems to be related to an expired certificate in your browser. 

You could try a few things:
1. Update Chrome
2. Make sure you are using Python 3.10+ and Selenium 4.9.1+
3. Add options to the webdriver, see: https://stackoverflow.com/questions/76742394/why-my-selenium-return-certificate-error

**Comment by shavster** [comment]
Thank you for the reply, and I'm sorry for wasting your time. Google is my friend... Thanks for making the code available.
